### ISSUE TITLE
concerning generating specific values

### ISSUE THREAD

**Issue by zhaoyizhaoyi** [zhanzecheng/IRNet#1]
Thanks for your paper,really brilliant!
Well, there are three kinds of actions present in your paper, "SelectColumn", "SelectTable" and "ApplyRule". But I wonder how you generate a specific string value like "food" or a number value which may appear in a limit clause like "limit 1". I guess such cases exist in where clauses. So the question is how do you generate such values without an action like "GenTokenAction"? 
Thanks~

**Comment by zhanzecheng** [comment]
Hi zhao,

Thanks for your Interest in our works.
Until now we only consider the exact set match score without values,  as mentioned in the task site(https://yale-lily.github.io/spider).

Best,
Zecheng

**Comment by zhaoyizhaoyi** [comment]
Thanks for your reply!
I see, so during evaluation, it is OK to ignore all the specific values. But I still wonder, during training, do you pre-process to overlook all the specific values? That is, when generating the action sequences, do you just overlook all the specific values?

**Comment by zhanzecheng** [comment]
Yes, the training action sequences do not include specific VALUES. We only generate the pre-order of SemQL which does not contain value cause. You could find more detail on our paper.

**Comment by zhaoyizhaoyi** [comment]
I understand. Thanks again!
Looking forward to your code release.
